version: '3.5'

services:
    app:
        image: pizelli/webserver:1.1
        volumes:
            - ./.docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
            - ./.docker/php-config.ini:/etc/php/7.4/apache2/conf.d/php-config.ini
            - ./:/var/www/html
        ports:
            - 8001:80
        tty: true

networks:
    default:
        external: true
        name: geral
